### ISSUE TITLE
Using the CircuitBreaker, how can I access the exception?

### ISSUE THREAD

**Issue by jansson** [michael-wolfenden/Polly#19]
How can I access the raised exception (for logging) when using the CircuitBreaker?

**Comment by LetMeCodeThis** [comment]
When your code throws an expcetion while using CircutBreaker policy then CB will throw your exception or BrokenCircuitException when the circuit state is broken (this policy does not swallow exceptions). So to access exception you need to use try/catch block.

**Comment by jansson** [comment]
Makes sense. Thanks!
