### ISSUE TITLE
Feature Request : Support Windows Phone 8.1 in the PCL project.

### ISSUE THREAD

**Issue by pdamp** [michael-wolfenden/Polly#20]
Hi,

I would like to see the PCL project also support a Windows 8.1 phone as well, would make development much easier when creating a PCL designed to be used from a Universal App targeting Windows 8 and a Windows Phone 8.1.

Thanks

**Comment by onovotny** [comment]
This is already supported by the csproj, but the NuGet portable- dir needs to include wpa81 in the string.

**Comment by michael-wolfenden** [comment]
pdamp, onovotny

I've just release a new version (2.2.0) that has corrected the nuget target.

Let me know if this has fixed this issue.

**Comment by onovotny** [comment]
:+1:

**Comment by pdamp** [comment]
Seems to be working just fine, thanks for the quick response.

**Comment by michael-wolfenden** [comment]
Thanks guys
