### ISSUE TITLE
The default sleep delegate does not block in the PCL assembly

### ISSUE THREAD

**Issue by JustinPierce** [michael-wolfenden/Polly#23]
When using Polly in a PCL, the default value for `SystemClock.Sleep` does not block. The result is that any retries from `RetryAndWait()` will be fired in rapid succession.

I'm using the following replacement in my code, and it seems to be working:

`SystemClock.Sleep = timespan => new ManualResetEvent(false).WaitOne(timespan);`

**Comment by michael-wolfenden** [comment]
Justin,

Thanks for the bug report. The issue is that `async span => await Task.Delay(span)` is not blocking, hence causing the issue you are seeing. I think I'll replace your suggestion of the `ManualResetEvent`
