### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by jeserra** [michael-wolfenden/Polly#28]
Hi. 
   I am trying to make a simple example for retry. But is not catching the exception. I try to send a new value in zero variable, but neither work. What is wrong with this code? Thx in advance. 

static long zero = 0;
        static void Main(string[] args)
        {
            try
            {

                var policy = Policy
                 .Handle<System.DivideByZeroException>()
                 .Retry(3, (exception, retryCount, context) =>
                 {
                     zero++;
                 });

                var result = policy.Execute(
                    () => DoSomething()
                );
            }
            catch(DivideByZeroException)
            {
                Console.WriteLine("No se porque estaria esto aqui");
            }
            catch(Exception ex)
            {
                Console.WriteLine( ex.TargetSite);
            }
             Console.ReadKey();

        }

        static long DoSomething()
        {
            long resultado = 1 / zero;
            return resultado;
        }

**Comment by michael-wolfenden** [comment]
Hi,

The reason that the `DivideByZeroException` is not being caught, is that the first time through, `DoSomething` executes `1/0` which cause a `DivideByZeroException` to be thrown. Polly will then retry, however in your retry handler, you are incrementing `zero`, so the next time we call `DoSomething`, it executes `1/1` which is valid and won't throw an exception, so no more retries are performed.

I have create a code sample at https://dotnetfiddle.net/Widget/NDjoJF which demonstrates how it should work.

Let me know if that answers your question

**Comment by jeserra** [comment]
Hi, 
   Thx for your quick anwer. I found that debugging in vstudio 2013 looks like the exception wasn't rety. Buy running from console was ok.
