### ISSUE TITLE
After final failure wrap and throw a new exception

### ISSUE THREAD

**Issue by bunceg** [michael-wolfenden/Polly#31]
Hi, 

I'm doing something like this:

return await Policy
	.Handle<Exception>(ex => _strategy.IsTransient(ex))
	.WaitAndRetryAsync(new[] 
		{ 
			TimeSpan.FromMilliseconds(250), 
			TimeSpan.FromMilliseconds(500), 
				TimeSpan.FromMilliseconds(750)
		}, (ex, retryCount) =>
		{
			retries = retries + 1;
			//TODO: Log
		})
		.ExecuteAsync(() => _decoratedAsync.ExecuteAsync(query)).ConfigureAwait(false);

This is a generic handler where I inject the strategy and the code to be run. However in some cases I need the handler to catch a final (e.g.) "Service Slow" exception and then raise a Service Unavailable instead. As this is a generic handler, it's only applicable in a few cases so I don't really want to write a custom handler with a try - catch for this.

Can this be done in Polly? (maybe use the retry count?)

**Comment by yftachman** [comment]
I think we should come at this from a different direction,
we should add to the policy builder a new method called AfterFinalRetry(Action<Exception> action)
and you an do what ever you'd like with the exception (wrap it, rethrow it, ignore it, w\e).
Of course the default behavior should remain the same (throw the exception after final retry), but if this method has been invoked on the policy it should override the default behavior.

I will try to do it this weekend...

**Comment by bunceg** [comment]
sounds good to me, thanks

**Comment by yftachman** [comment]
Hey,
made this fork
https://github.com/yftachman/Polly

should contain the changes you need.
if there are any problems with it let me know.
i'm not that familiar with this project so problems may arise 

gl hf :)

**Comment by vincpa** [comment]
I'd like a little more consistency with the .NET framework.

Instead of having a AfterFinalRetryFailure, perhaps something more generic where you tell it when you want a delegate to run.

We have this in TPL.
Task.Factory.StartNew(() => {})
  		    .ContinueWith(task => { /* Do stuff*/ }, TaskContinuationOptions.OnlyOnFaulted)

I guess this means it would come back to a solution which uses a Policy

**Comment by tapmantwo** [comment]
This would be super useful...

**Comment by vincpa** [comment]
@michael-wolfenden is this something you would consider merging in to the main branch?

**Comment by michael-wolfenden** [comment]
I have just released the latest version (2.2.3) with includes post execution support. This should allow you do what you are suggesting.

**Comment by bunceg** [comment]
Thanks for this
